version: '3.8'
services:
  appdb:
    image: postgres:10
    container_name: 'appdb'
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "15432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d

volumes:
  database:
    driver: local